### ISSUE TITLE
Schematic connections

### ISSUE THREAD

**Issue by hecguillem** [HomeKidd/ESP8266-HomeKit-Stateless-Button-Elgato-Eve-Button#2]
First of all thanks for your great work.

I Am interested on this project, but I don’t find schematic connections.

Where I can find it?
Thanks

**Comment by HomeKidd** [comment]
> First of all thanks for your great work.
> 
> I Am interested on this project, but I don’t find schematic connections.
> 
> Where I can find it?
> Thanks

Hi! Thanks 😄 

There are no schematic currently, because all you need is one button connected to `GND` and `GPIO0` as shown in the [Wiki page](https://github.com/HomeKidd/ESP8266-HomeKit-Stateless-Button-Elgato-Eve-Button/wiki/Hardware-setup#connections)
