### ISSUE TITLE
Connecting to ESP8266 WiFi to setup

### ISSUE THREAD

**Issue by ChopsKingsland** [HomeKidd/ESP8266-HomeKit-Stateless-Button-Elgato-Eve-Button#4]
I have flashed my ESP8266, but I can't connect to its WiFi to set it up. I have tried connecting to LCM-(STA MAC ADDRESS) with and without dashes, and LCM-(AP MAC ADDRESS), with and without dashes, it still won't connect!

**Comment by HomeKidd** [comment]
Use the non OTA version by simply flashing the main.bin file, it should work. The OTA part is not my code and its unreliable! Also make sure to flash it with the right settings

**Comment by ChopsKingsland** [comment]
If I do the non-OTA version, how do I connect it to my WiFi?

**Comment by HomeKidd** [comment]
> If I do the non-OTA version, how do I connect it to my WiFi?

The same way as the OTA version.
Did you read the [Wiki](https://github.com/HomeKidd/ESP8266-HomeKit-Stateless-Button-Elgato-Eve-Button/wiki)?

**Comment by ChopsKingsland** [comment]
I've read the Wiki, but I'm confused what mac address I use (see below), and whether its LCM-[mac address] or HomeKid-[mac address]
![image](https://user-images.githubusercontent.com/18499854/85946581-3f0a3a80-b93d-11ea-8a40-9194f54bf4ff.png)

**Comment by ChopsKingsland** [comment]
I have connected it to my WiFi, but I can't connect it to homekit

**Comment by ChopsKingsland** [comment]
When I restart the ESP8266, and use a serial monitor to see what is happening, I get the following:
```
Flash Size:   32 Mbit
Flash Mode:   DIO
Flash Speed:  40 MHz
rBoot Option: Big flash
rBoot Option: RTC data

Booting rom 0 at 2000, load addr 6d010.
,⸮+Zꨥ⸮⸮UU(U⸮⸮Z⸮Ք⸮⸮+R⸮UT%⸮Ҩ⸮R*⸮-UU⸮TE*⸮⸮V+⸮⸮+R⸮⸮U⸮T⸮⸮ҪUZҰ⸮⸮⸮⸮⸮⸮0x3fff43a0, prio:12, stack:200

ESP-Open-SDK ver: 0.0.1 compiled @ Apr  4 2020 18:18:13
phy ver: 273, pp ver: 8.3



  HomeKid  

Developed by @Homekidd 

  Button's Firmware Version: 1.0.4 for Hardware 1.0.0

!!! HomeKid ! Using Button at GPIO0.
>>> wifi_config: Initializing WiFi config
!!! wifi_config: No configuration found
>>> wifi_config: Starting AP mode
>>> wifi_config: Starting DHCP server
mode : sta(50:02:91:ec:68:5e) + softAP(52:02:91:ec:68:5e)
add if0
add if1
bcn 100
>>> wifi_config: Starting WiFi scan
>>> wifi_config: Starting DNS server
>>> wifi_config: Starting HTTP server
scandone
scandone
scandone
scandone
scandone
scandone
scandone
scandone
scandone
scandone
scandone
scandone

```

and it just keeps saying `scandone` continually. I was wondering if `!!! wifi_config: No configuration found` has something to do with it?

**Comment by ChopsKingsland** [comment]
When I restart the ESP8266, and use a serial monitor to see what is happening, I get the following:

```
Flash Size:   32 Mbit
Flash Mode:   DIO
Flash Speed:  40 MHz
rBoot Option: Big flash
rBoot Option: RTC data

Booting rom 0 at 2000, load addr 6d010.
,⸮+Zꨥ⸮⸮UU(U⸮⸮Z⸮Ք⸮⸮+R⸮UT�%⸮Ҩ⸮R*⸮-UU⸮TE*⸮⸮V+⸮⸮+R⸮⸮U⸮T⸮⸮ҪUZҰ⸮⸮⸮⸮⸮⸮0x3fff43a0, prio:12, stack:200

ESP-Open-SDK ver: 0.0.1 compiled @ Apr  4 2020 18:18:13
phy ver: 273, pp ver: 8.3



  HomeKid  

Developed by @Homekidd 

  Button's Firmware Version: 1.0.4 for Hardware 1.0.0

!!! HomeKid ! Using Button at GPIO0.
>>> wifi_config: Initializing WiFi config
!!! wifi_config: No configuration found
>>> wifi_config: Starting AP mode
>>> wifi_config: Starting DHCP server
mode : sta(50:02:**:**:**:**) + softAP(52:02:**:**:**:**)
add if0
add if1
bcn 100
>>> wifi_config: Starting WiFi scan
>>> wifi_config: Starting DNS server
>>> wifi_config: Starting HTTP server
scandone
scandone
scandone
scandone
scandone
scandone
scandone
scandone
scandone
scandone
scandone
scandone

```
and it just keeps saying `scandone` continually. I was wondering if `!!! wifi_config: No configuration found` has something to do with it?

**Comment by HomeKidd** [comment]
`No configuration found` means that you didnt entered you wi-fi name and password as it in the [wiki](https://github.com/HomeKidd/ESP8266-HomeKit-Stateless-Button-Elgato-Eve-Button/wiki/Setup#wi-fi-setup)! 

You dont need to you anything with the Mac address, each esp has a unique one to identify them. 


Simply take your iOS device, go to Setting -> Wi-Fi, and search for an Wi-fi  called HomeKid-xxxxxx (where the x are a unique Mac addres). After a few second a web page will pop-up, select your wi-fi and enter your wi-fi password as i’ve also mentioned in the Wiki too.

**Comment by ChopsKingsland** [comment]
It originally showed up as LCM-****** and I configured it using that, but now HomeKid-****** shows up

**Comment by ChopsKingsland** [comment]
I just tried connecting to HomeKid-****** with the default password of `12345678` and it says incorrect password! What else could the password be?

**Comment by ChopsKingsland** [comment]
I got it working! Thanks for the help!
